### ISSUE TITLE
Option to add multiple accounts from the same cloud service (e.g. Dropbox)

### ISSUE THREAD

**Issue by johnnydebs** [cryptomator/cryptomator-ios#142] opened 2021-03-03 12:07 UTC
### Summary

Many people have multiple cloud accounts with the same provider (e.g. Dropbox personal & Professional).  Currently it seems that Cryptomator allows only one account (stated in documentation https://docs.cryptomator.org/en/latest/ios/vault-management/).  This is an important feature to have!

### Motivation

Give users more options especially those that have multiple accounts, making it easier for people to transition! 

### Considered Alternatives

I’ve used Boxcryptor, and they have no limitation on accounts from the same provider.  The only alternative currently I’ve thought of with Cryptomator is segregating providers by using for example Dropbox professional for business vaults and iCloud or other for personal vaults.  This is not idea as it may imply additional subscription costs for users with high storage requirements!

### Additional Context

I believe the above was sufficient.

**Comment by tobihagemann** [comment] 2021-03-03 12:48
Duplicate of #86

Quick update: We are currently working on that, which is part of the "new" iOS app!

**Closed by tobihagemann** 2021-03-03 12:48 UTC

**Comment by johnnydebs** [comment] 2021-03-03 13:30
Awesome thank you!On Wed, Mar 3, 2021 at 14:48, Tobias Hagemann <notifications@github.com> wrote:  
Duplicate of #86
Quick update: We are currently working on that, which is part of the "new" iOS app!
