### ISSUE TITLE
Select multiple files IOS 13

### ISSUE THREAD

**Issue by hume1991** [cryptomator/cryptomator-ios#122] opened 2020-04-17 09:32 UTC
At the moment, each file on the iPhone has to be deleted individually, since more selection is not possible. However, it is possible to delete the folder where the files are contained.

Best regards

Christian Huml

**Comment by tobihagemann** [comment] 2020-04-17 09:52
Duplicate of #52

**Closed by tobihagemann** 2020-04-17 09:52 UTC
Labels: type:duplicate
