### ISSUE TITLE
ios onedrive edu login failed with msalerrordomain

### ISSUE THREAD

**Issue by jiahao1889** [cryptomator/cryptomator-ios#174] opened 2021-12-09 19:16 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

ios onedrive edu login failed with msalerrordomain

### What software is involved?

- Operating System: ipad os
- Cryptomator: 1.6.1

### Steps to Reproduce

1. add vault or select existed
2. choose onedrive
3. Login

### Expected Behavior

Login successfully 

### Actual Behavior

![48336CA7-0C36-446C-8932-2171CE5BFFA6](https://user-images.githubusercontent.com/432505/145460848-73f208e6-e557-4284-926d-4557b2ef3a95.png)
Login failed

### Reproducibility

Always

**Comment by tobihagemann** [comment] 2021-12-09 20:17
Duplicate of #173

**Closed by tobihagemann** 2021-12-09 20:17 UTC
Labels: type:duplicate
