### ISSUE TITLE
Pasted text into IMessage Results in Cryptomator file?

### ISSUE THREAD

**Issue by wangkesen** [cryptomator/cryptomator-ios#94] opened 2017-07-07 21:45 UTC
Is weird I don’t know what the cause of this bug is but after copying text from any app and then pasting into iMessage, it outputs a file with the Cryptomator logo.![Explanation](http://i.imgur.com/08USCnk.jpg)

**Comment by tobihagemann** [comment] 2017-07-08 08:25
Thank you for your bug report! 👍 First I was like: What? :joy: But then I remembered that you've already updated to iOS 11. Yep, I can reproduce the issue on my iPad with iOS 11 beta 2. Now I'm not so sure if we configured something wrong but in my opinion it's an upstream bug in Messages. I'll file a bug report to Apple and see how it goes from there. :smile:

**Comment by tobihagemann** [comment] 2017-07-10 09:21
Just uninstalled Cryptomator and tried again. Now the file icon looks like the one from Documents by Readdle. I suppose it's "just" a Messages bug. :joy: I'll still file a bug report to Apple but maybe it's already a known issue. :smile:

**Comment by tobihagemann** [comment] 2017-07-10 17:56
Oh well, seems to be fixed in iOS 11 beta 3. Can you confirm @wangkesen? :smile:

**Closed** 2018-06-17 14:59 UTC
Labels: type:upstream-bug
