### ISSUE TITLE
Read and write vaults in arbitrary Document Providers

### ISSUE THREAD

**Issue by 75th** [cryptomator/cryptomator-ios#70] opened 2016-12-19 04:36 UTC
(Obligatory: Cryptomator 1.2.0, iPhone 6, iOS 10.2)

Hi, I'm new to Cryptomator and am looking forward to getting to use it. I'm in the middle of switching from Dropbox to Sync.com, and I'm having the issue where my Cryptomator iCloud Drive folder isn't syncing to my Mac, so I'm kind of in a holding pattern at the moment. I thought about making a "Support Sync.com" request, but I saw that there are three or four other "Support [SERVICE]" issues already.

So what I'm wondering is whether it'd be possible to make Cryptomator access (and write to) vaults stored in any app that implements a Document Provider. That's kind of a table-stakes feature for any cloud service these days, and it'd be a good way to cover almost any service that doesn't have a WebDAV interface.

The problem is that I'm not sure I've ever seen an app that handles Document Providers in a completely seamless way; it seems like they all make a copy of the file and then make you manually propagate your changes, or something like that. So it may be extremely difficult or impossible to do this satisfactorily.

I'd love to hear what the developers think about this idea, but if it doesn't look good I guess I'll come back later and request Sync support after all. :)

**Comment by tobihagemann** [comment] 2016-12-19 09:56
It looks like Sync (sync.com) doesn't have any APIs for developers. I don't think we can support Sync at all. Maybe I have overlooked something?

Not sure if you've seen it, but we're planning to integrate the "Open" and "Move" operations of the Document Provider App Extension (#13). Unfortunately, it's a non-trivial task due to the encryption, but this is something that we'd like to implement, because it'd enhance the user experience tremendously (e.g. with Microsoft Office, which currently is a pita).

But this wouldn't solve your issue, because this isn't really used for "chaining" cloud storage services. It may work, but I also think that it wouldn't be seamless.

I would say for now that this issue is somehow a duplicate of #13, because we're bound to the available interfaces by iOS, so there is no other operation that import, export, open, and move. Sync support would be another issue, but as I've mentioned, I'm not sure if that's possible.

**Closed by tobihagemann** 2016-12-19 09:56 UTC
