### ISSUE TITLE
Auto-Lock not locking on Instant Setting

### ISSUE THREAD

**Issue by hoveeman** [cryptomator/cryptomator-ios#89] opened 2017-06-26 00:43 UTC
## Basic Info

This is a bug report.

I'm using iOS in version: 10.3.2

I'm running Cryptomator in version: 1.2.3

## Description

I have Google Drive set up in the iOS app with Touch-ID enabled and have Auto-Lock set to Instant. 

I unlock the app with Touch-ID, access my files, hit the home button and leave cryptomator, open another app, then go back to cryptomator and my vault has the unlocked symbol next to it and I can access the files without having to unlock the vault. The behavior is the same if I double click the home button and access cryptomator from recent apps or press the home button, go to the springboard, and open cryptomator from there.

My expected behavior is for any time cryptomator leaves focus as the primary app, the vault locks instantly.

**Comment by tobihagemann** [comment] 2017-06-26 09:38
Hi @hoveeman, thank you for your bug report! 👍 We've recently received a similar report but were never able to reproduce the issue. I tried the steps again you've described but it's all working here.

Your expectation is absolutely correct, Cryptomator should lock all vaults instantly after it has been sent to the background.

I think I'm onto something right now. I did a lot of experimenting again and occasionally I was able to reproduce the issue.

Could you try the following as a workaround:
- Terminate the application (double-click the home button and swipe Cryptomator up)

Do you still have the issue after that?

**Comment by tobihagemann** [comment] 2017-06-26 10:33
We found the issue. I'm surprised that it didn't come up earlier. It happens when you open up a view that loads the vaults list. Touch ID settings is one example.

Will be fixed with the next update. In the meantime, don't open up the Touch ID settings. 😆 If you do because you'd like to change the settings, restart the app afterwards.

**Comment by hoveeman** [comment] 2017-06-26 12:30
Thank you @tobihagemann! I tried your steps to reproduce by going to the Touch ID settings and it happens every time keeping the vault un-locked. If I terminate the application it does lock the vault and behaves as expected. In the mean time I will stay out of the Touch ID settings. :) Thanks for your support!

**Closed** 2017-07-02 16:46 UTC
Labels: type:bug
