### ISSUE TITLE
Swiping between files and back gesture

### ISSUE THREAD

**Issue by pawelostr** [cryptomator/cryptomator-ios#132] opened 2020-10-11 12:01 UTC
## Basic Info

I'm using iOS in version: 14.0.1

I'm running Cryptomator in version: 1.5.0 

## Description

Basic navigation like swiping between pdf's and images should be added, and back gesture seems to be working only on images.

**Comment by tobihagemann** [comment] 2020-10-12 06:42
Duplicate of #12

**Closed by tobihagemann** 2020-10-12 06:42 UTC
Labels: type:duplicate
