### ISSUE TITLE
Bulk transfer and Pictures Navigation

### ISSUE THREAD

**Issue by MarkJaafar** [cryptomator/cryptomator-ios#65] opened 2016-11-21 18:04 UTC
### Basic Info
- I'm running Cryptomator on: [iPhone, iPad, iPod touch]
- I'm using Cryptomator in version: 1.2.0

### Description
1- Using the iPhone/iPad items can be uploaded one by one (bulk), It takes long time to upload them to the vault. 
Pls add a way to select several files to upload at once.
2- When you press on a picture to view you must exit and hit another one. I suggest to add a swipe left and right to navigate the other pictures.

**Comment by tobihagemann** [comment] 2016-11-21 18:11
Thank you for your feedback!

Reg. 1:

Inside Cryptomator: You can already multi-select items from the photo library. I know it doesn't work if you choose another source, but that's out of our control, if we use the Document Provider by iOS.

From another app: Depending on the app you're using, you can use their(!) app to export the files to Cryptomator in bulk. You may have to activate Cryptomator's app extension first (bottom row with the monochrome icons). But that's also out of our control, because it's dependent on the other app. I don't think there is anything to add/fix in Cryptomator.

Reg. 2: Duplicate of #12

**Closed by tobihagemann** 2016-11-21 18:11 UTC
