### ISSUE TITLE
[iOS] Shared folder can’t be showed in Onedrive

### ISSUE THREAD

**Issue by giantrule** [cryptomator/cryptomator-ios#133] opened 2020-11-07 03:44 UTC
## Basic info
I'm using iOS in version: 12.4.8

I'm running Cryptomator in version: 1.5.0 (718)
(You can check the version in the Cryptomator settings under "About Cryptomator".)

## Description
My friend and I are sharing a Vault folder on Onedrive. The shared folder can be display on Onedrive website and Onedrive client on Windows. However, using Cryptomator, I can’t found this shared folder. 
Please fix it.

**Comment by tobihagemann** [comment] 2021-02-08 08:24
I was unable to reproduce the issue. If someone shared a folder with you, you have to add it your "own" OneDrive, see: https://support.microsoft.com/en-us/office/add-and-sync-shared-folders-to-onedrive-for-home-8a63cd47-1526-4cd8-bd09-ee3f9bfc1504#bkmk_add

Or are you using OneDrive for Business? This might be a different issue then.

**Comment by tobihagemann** [comment] 2021-02-08 13:21
Closing this in favor of #139

**Closed by tobihagemann** 2021-02-08 13:21 UTC
Labels: storage:onedrive
