### ISSUE TITLE
Upload large files to Dropbox, iCloud Drive, and OneDrive doesn't work

### ISSUE THREAD

**Issue by gatias** [cryptomator/cryptomator-ios#27] opened 2016-04-24 14:13 UTC
### Basic Info

- I'm running Cryptomator on: [iPhone], IPhone 6s running IOS 9.3.1
- I'm using Cryptomator in version: [1.0.2]

### Description

Upload of a movie file (~3 minutes long) through "send-to" dialog encrypts the file and tries to upload it. Upload doesn't show any progress and aborts without a message after around 1 minute showing the file selection screen again. No progress in upload during the 1 minute duration (only a very small piece of the upload circle is filled, without any progress).

Multiple upload of movie files through file selection in cryptomator doesn't work either. Selection of files possible, no encryption or upload screen after selecting the files. Re-direction to the cryptomator folder.

Upload of an image into the same folder connected to my dropbox account is possible without any problems.

**Comment by MuscleRumble** [comment] 2016-04-24 14:20
Thank you for your bug report! I'll try to confirm it in the next couple of days. I've recently fixed a bug regarding video upload, that's why it should be fixed with the next update. Didn't try it with ~3 minute long videos though, that's why I'll do some further testing.

**Comment by gatias** [comment] 2016-04-24 14:23
Alright, sounds good. If you need further information/help, don't hesitate to contact me.

**Comment by MuscleRumble** [comment] 2016-05-05 23:04
I can confirm the issue. The bugfix I've mentioned was only regarding the visual aspect, so that you'll at least see the progress with the next update. However, at some point the upload aborts with an error `NSURLErrorDomain -1001`, similar to here: https://www.dropboxforum.com/hc/en-us/community/posts/201887309-Error-1001-The-operation-couldn-t-be-completed-

I'll have to experiment with chunked uploading on Dropbox. I've checked the other cloud storage services and I wasn't amused:

- iCloud Drive just crashed, I can't take this seriously anymore 😂
- OneDrive timed out similar to Dropbox 😕

Google Drive and WebDAV (coming with 1.1) were the clear winners and didn't timeout 🎉 (WebDAV could be a coincidence though, because strictly speaking my ownCloud server didn't timeout 😆)

This will take some time to implement and fix across the other cloud storage services as well (if possible), that's why I'll postpone this fix to the next patch (following 1.1).

**Comment by tobihagemann** [comment] 2016-09-11 18:02
Fixed

**Closed by tobihagemann** 2016-09-11 18:02 UTC
Labels: cloud:dropbox, cloud:icloud-drive, cloud:onedrive, state:confirmed, type:bug
