### ISSUE TITLE
Cannot upload from Photos with iCloud Photo Library's storage optimization enabled

### ISSUE THREAD

**Issue by abgit** [cryptomator/cryptomator-ios#74] opened 2017-01-31 13:47 UTC
### Basic Info

- I'm running Cryptomator on: **iPhone 7 - ios 10.2.1 or ios 10.3**
- I'm using Cryptomator in version: **1.2.0**

### Description

When i try to upload a image to cryptomator i get an error "`Nothing has been uploaded`" and file is not uploaded.

### Steps to reproduce:
1. open cryptomator on iphone 7 with ios 10.2.1 (or ios 10.3)
2. select a vault (i got error on icloud or dropbox vaults)
3. click on 'o o o' option menu
4. select "upload file"
5. select first menu option "Photos"
6. select any photo from iphone
7. error message "`Nothing has been uploaded`" is displayed

btw, if i select a iclouddrive or dropbox file to upload (instead of a local Photo) it works fine.

best,
Francisco Azevedo

**Comment by abgit** [comment] 2017-01-31 14:13
After some testing.. i found that i could upload a local Photo but only if that photo is in cache. On all other photos i got "`Nothing has been uploaded`".

I have all my photo galery with icloud optimization [(Optimize iPhone Storage - ON)](https://support.apple.com/en-us/HT204264). This means that i only have an optimized version of each image on iphone storage and full image file is on icloud. If i select an image for first time on iPhone native image manager, i can see that image is fully downloaded from icloud.. and then, if i select that specific image on cryptomator to upload i have no problem.

Sounds like an issue between cryptomator and ios.. Seems that cryptomator cannot wait for ios to download full file if not exists on local iphone and aborts.

**Comment by tobihagemann** [comment] 2017-01-31 18:57
Thank you for reporting this issue! :+1: We'll look into it.

**Comment by abgit** [comment] 2017-02-11 12:45
Hi, any news on this?

**Comment by tobihagemann** [comment] 2017-02-12 09:46
Not yet, we have to set up a test environment first, because none of us is actually using iCloud Photo Library. 😅 Will have the opportunity to do so in the next couple of weeks. Sorry for the delay!

**Comment by abgit** [comment] 2017-03-29 08:18
hi @tobihagemann ,
Cryptomator-ios `v1.2.1` released today and problem persists.

Any news on this ?

**Comment by tobihagemann** [comment] 2017-03-29 08:21
That's correct. We'll look into it for the next patch 1.2.2, because we've addressed many other issues in 1.2.1 that we wanted to release as soon as possible. Thank you for your patience!

**Comment by abgit** [comment] 2017-03-29 09:30
Thanks.
btw, i have same behavior when using cryptomator on latest ios ( v10.3 ).

**Comment by tobihagemann** [comment] 2017-04-11 13:06
@abgit Finally, I came around to get a test environment up and running. I've enabled iCloud Photo Library's storage optimization. Now, I'm not exactly sure how to trigger a photo/video being optimized in order to reproduce the issue. I have the feeling that everything happens automatically, which makes it harder to reproduce.

I guess I'll just play around for now, but if you have an easy way to reproduce the issue "from scratch", please let me know! :)

**Comment by abgit** [comment] 2017-04-11 13:50
Now, go to icloud.com and, on photos, upload a new one directly from your browser.

That image must be sync to your Iphone photos app. I think Iphone must be connected to a wifi net, with battery (80%+) and locked, to sync from icloud.

On Iphone, open photos app to check if image is already there but dont open the image (because Iphone will try to download the original version on background). That image is a optimized photo.

If image is there, open cryptomator and try to select and upload that specific image to a vault. Cryptomator should download the original and then upload (like other apps) instead of error.

best,

**Comment by tobihagemann** [comment] 2017-04-11 14:12
Thanks, I was already fiddling around with icloud.com, but was struggling. 😆 I think I've got a reproducable state now. 👍

**Comment by tobihagemann** [comment] 2017-04-13 20:03
Will be fixed in 1.2.2. The update is currently "waiting for review".

**Closed by tobihagemann** 2017-04-13 20:03 UTC
Labels: state:confirmed, type:bug
