### ISSUE TITLE
Camera Upload

### ISSUE THREAD

**Issue by vesparny** [cryptomator/cryptomator-ios#72] opened 2017-01-10 13:13 UTC
### Basic Info

- I'm running Cryptomator on: iPhone
- I'm using Cryptomator in version: 1.2.0

### Description

Any chance to support a camera Upload feature?

**Comment by tobihagemann** [comment] 2017-01-10 13:52
Hey! Do you mean #69?

**Comment by vesparny** [comment] 2017-01-10 15:23
Nope,
I meant a feature that uploads any picture taken by the camera directly to the vault.
Something like the dropbox app does.

**Comment by tobihagemann** [comment] 2017-01-10 15:27
Ah, understood! Then it's a duplicate of #20. :smile: Thank you for your suggestion!

**Closed by tobihagemann** 2017-01-10 15:27 UTC
