### ISSUE TITLE
Error message > "SETODirectoryBrowserErrorDomain-Fehler 0"

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/cryptomator-ios#15] opened 2016-03-15 22:51 UTC
_Moved from [cryptomator/cryptomator](/cryptomator/cryptomator/issues/183), reported by @MS191:_

Receive the following error message ("SETODirectoryBrowserErrorDomain-Fehler 0") when trying to open/include *.cryptomator file in iCloudDrive on other device that the one it was created with. Example:

* File "Test1" created on iPad in iCloudDrive
* Then Tried to open this file on iPhone > Above error message appears

**Comment by MuscleRumble** [comment] 2016-03-20 12:59
Related to #11

**Comment by MuscleRumble** [comment] 2016-03-28 14:18
Error messages are now localized. However this particular error is a duplicate of #11, therefore closing this.

**Closed by MuscleRumble** 2016-03-28 14:18 UTC
Labels: bug
