### ISSUE TITLE
Ability to select/export multiple files or folder

### ISSUE THREAD

**Issue by wangkesen** [cryptomator/cryptomator-ios#84] opened 2017-05-07 14:28 UTC
I know this is a function that is partially available in the photos stock app as it will let you select multiple photos to import from your iOS camera roll to your Cryptomator vault, but it would be nice to see the functionality of being able to select more then one file in the Cryptomator vault itself. Right now it's only limited to file by file transfer. Or even being able to transfer a whole folder. You can move the folders in app yes but you can't use the function to then export out of the vault a whole folder or vice versa.

**Comment by tobihagemann** [comment] 2017-05-07 17:52
Duplicate of #52

**Closed by tobihagemann** 2017-05-07 17:52 UTC
