### ISSUE TITLE
Cryptomator seems hanging when browsing folders

### ISSUE THREAD

**Issue by marcopallotta** [cryptomator/cryptomator-ios#172] opened 2021-12-08 14:09 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Cryptomator seems hanging when browsing folders. In fact sometimes (but this happens very often) you cannot browse a folder (the interface shows the rolling icon of folder access). At this point you have to go to parent directory and try again.

### What software is involved?

- iPadOS 15.1 
- Cryptomator 1.6.1: 
- …

### Steps to Reproduce

1. Open cryptomator vault
2. Browse folders and their subfolder
3. …

### Expected Behavior

You expect to access the folder

### Actual Behavior

The interface seems to hang.

### Reproducibility

Intermittent

**Comment by tobihagemann** [comment] 2021-12-09 08:46
Even though you're experiencing this issue in a different spot, it's basically a duplicate of #171.

**Closed by tobihagemann** 2021-12-09 08:46 UTC
Labels: type:duplicate
