### ISSUE TITLE
thumbnail

### ISSUE THREAD

**Issue by andreas-dc** [cryptomator/cryptomator-ios#125] opened 2020-05-19 20:39 UTC
I'm using iOS in version: 13.4.1 (iPhone XR)

I'm running Cryptomator in version: 1.5.0 (718)

I successfully created a vault via webdav inside my nextcloud storage. After creating a folder and uploading some pics I noticed something strange. Whenever I click on a file name, the preview of the pic comes up. Perfect. But as soon as I close it, the generic icon in front of the corresponding file name flickers. It seems, like a thumbnail „wants“ to come up. To no avail.

It would be nice to have a small thumbnail in front of a pic‘s file name. Only in front of these, who have been downloaded already.

**Comment by tobihagemann** [comment] 2020-05-20 07:45
Duplicate of #73

**Closed by tobihagemann** 2020-05-20 07:45 UTC
