### ISSUE TITLE
Audio stops after 8 seconds

### ISSUE THREAD

**Issue by olyroad** [cryptomator/cryptomator-ios#137] opened 2021-01-05 03:35 UTC
### Description

I set an audio to play through the Cryptomator App player. I turn the screen of the iPhone off and let the audio play. The audio stops after about 8 seconds. 

### System Setup

* Operating system and version: iOS 14.3
* Cryptomator version: 1.5.1 (732)
* Volume type: WebDAV

### Steps to Reproduce

1. Open the App
2. Connect to an encrypted vault of yours
3. Play an MP3 from within your encrypted vault. 
4. Turn off the screen of your iPhone but let the MP3 continue playing
5. It takes about 8 seconds. The audio will stop

#### Expected Behavior

The audio should play from the Cryptomator audio player without stopping. Continuously

#### Actual Behavior

The audio, playing from the Cryptomator audio player will stop playing in about 8 seconds

#### Reproducibility

Always

### Additional Information

I thought the reason might be because maybe the vault locks. I changed the lock settings to never lock. The problem persists. Therefore, i found no way to solve this from the available settings. It seems like a bug.

**Comment by tobihagemann** [comment] 2021-01-07 14:51
I'm unable to reproduce the issue. I was able to listen to an audio file for several minutes.

**Comment by olyroad** [comment] 2021-01-10 04:15
Can i record this and upload a video demonstrating it? I am on iPhone 12 Pro.

**Comment by StanoRiga** [comment] 2021-01-10 10:57
Tried to reproduce that on my XS Max as well and couldn't. (WebDAV to own Server and OneDrive for Business)
Receiving the 12 Pro Max soon (I hope) and will try to reproduce again.

**Comment by tobihagemann** [comment] 2021-01-11 11:37
For the record, I tested it on an iPhone 12, also iOS 14.3.

I don't believe that a recording will help, I just don't have any idea what the cause might be. Technically, the file is being downloaded _completely_ (and not streamed!) and the playback happens using a regular [`QLPreviewController`](https://developer.apple.com/documentation/quicklook/qlpreviewcontroller), so it's basically handled by the operating system.

If the audio stops and you return to Cryptomator, can you continue the audio or is the playback screen "gone"?

**Comment by olyroad** [comment] 2021-01-11 15:14
@tobihagemann I confirm that the audio gets fully downloaded and decrypted once I click to play. It starts playing the audio. I click on the button to switch off the screen of the phone. The audio continues playing. I click on the right button again, and I see the player on my screen (same as with all audio apps, when the audio appears on the main screen before we unlock the phone's screen). I switch off the phone's screen again. And I wait. It takes about 8 seconds (maybe a little more than 8 seconds) and the audio stops again. I then log on onto my phone again. And I can push the play button again. When I do it, the audio continues playing from where it was left. I.e. it resumes. It does not start from the beginning. And the audio appears all as downloaded, therefore, it does not download the audio again. Also, to your question, the playback screen is not "gone". It's there. It's exactly as if I had clicked on "Pause".

**Comment by tobihagemann** [comment] 2021-01-11 15:19
Thank you for the detailed explanation! Are you playing the audio from your phone or via earbuds, Bluetooth devices, or anything like that?

**Comment by tobihagemann** [comment] 2021-01-11 15:29
Maybe this helps? https://discussions.apple.com/thread/7303503

Just set up a live photo as my wallpaper and I was able to reproduce the issue. Oh my god, Apple...

**Comment by olyroad** [comment] 2021-01-11 15:41
@tobihagemann  No bluetooth devices or anything. Directly from the phone and the phone's speakers.
I am glad you managed to reproduce the issue. And glad we identified what's happening.

**Comment by tobihagemann** [comment] 2021-01-11 15:57
Closing this issue since this is an upstream bug and has been one for many years in iOS.

### Workaround
Don't use a live photo as wallpaper.

**Closed by tobihagemann** 2021-01-11 15:57 UTC
Labels: state:has-workaround, type:upstream-bug
