### ISSUE TITLE
Basic caching for files

### ISSUE THREAD

**Issue by ahelpingchip** [cryptomator/cryptomator-ios#79] opened 2017-03-27 18:43 UTC
## Basic Info

This is a feature request.

I'm using iOS in version: iOS 10.2

I'm running Cryptomator in version: 1.2.0 (389)  

## Description

Hi! I've seen issues #44 and #45, but what I am suggesting is basic caching functionality, with a cap on the total cache size.

e.g. When the user opens a previously-unopened file, the file is stored in cache for future access. Subsequent accesses use the local cache, unless the file has been modified since. Files are expunged from cache when the cache is full, in reverse order of last accessed time. (Oldest files first.)

In terms of UI/UX and state management, I think this would be easier to do than manually defining files/folders to keep offline, and would suit the needs of most users while having a simpler interaction model. 

There can be settings for enabling cache, the max cache size, and a flush cache button. Here's what it looks like on the old Boxcryptor (which I've replaced with Cryptomator) —

![img_1439](https://cloud.githubusercontent.com/assets/735119/24372364/967d0a5e-12e2-11e7-8f07-6b78e2c8cf86.PNG)

Thanks for Cryptomator! :)

**Comment by tobihagemann** [comment] 2017-03-28 10:20
Thank you for your feature request! :+1:

I'd say it's a duplicate of #17, but you've added some useful information. I've always thought about a cache that clears itself after every "session". You are proposing a persistent cache.

Furthermore, this persistent cache might replace many use cases of the offline functionality proposed in #44 and #45. Veeery interesting and I quite like the idea. It won't replace the offline functionality though, but I think it's an easier start, because there aren't any new UI elements other than additional settings.

I'll close this one in favor of #17, but I'll add the new information there.

**Closed by tobihagemann** 2017-03-28 10:20 UTC
